TERMUX_PKG_HOMEPAGE=https://codeberg.org/dnkl/fcft
TERMUX_PKG_DESCRIPTION="A small font loading and glyph rasterization library"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_VERSION="3.1.8"
TERMUX_PKG_SRCURL=https://codeberg.org/dnkl/fcft/archive/${TERMUX_PKG_VERSION[0]}.tar.gz
TERMUX_PKG_SHA256=f48c793f354b8be95477e475dde7c98ac9d2628c52ecb42029dc6d20b52d787c
TERMUX_PKG_DEPENDS="fontconfig, freetype, harfbuzz, libpixman, libwayland, libxkbcommon, utf8proc"
TERMUX_PKG_BUILD_DEPENDS="libtllist"
